version: '2'

services:
  hapi-starter-kit:
    build:
      context: .
      args:
        SSH_KEY: ${SSH_KEY}
    # Disable mounting of volumes if packages are not installed locally.
    volumes:
      - .:/app
    # Wait for aerospike to be available on port 3000 before starting application
    # command: ["./bin/wait-for-it.sh", "aerospike:3000", "--", "yarn", "start"]
    env_file:
      - bin/dev.env
    # Pick ports from config or env.
    ports:
      - "3000:3000"
    links:
      - statsd

  statsd:
    image: hopsoft/graphite-statsd
    # Pick ports from env or config
    ports:
      - "3002:80"
      - "2003:2003"
      - "8125:8125/udp"
    # Disable graphana by default.
#    links:
#      - grafana

   # Disable grafana by default
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3001:3000"
